# Generated by Django 6.0.7 on 2026-07-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('style', models.CharField(choices=[('realism', 'Realism'), ('hyperrealism', 'Hyperrealism'), ('linework', 'Linework'), ('cartoon', 'Cartoon'), ('surrealism', 'Surrealism')], max_length=20)),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], max_length=5)),
                ('subjects', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('extra', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('CA', 'Common Art'), ('IA', 'Important Art'), ('VIA', 'Very Important Art')], default='CA', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('balance_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
