# Generated by Django 6.0.7 on 2026-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('realism', 'Realism'), ('hyperrealism', 'Hyperrealism'), ('linework', 'Linework'), ('cartoon', 'Cartoon'), ('surrealism', 'Surrealism')], max_length=25)),
                ('size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('ngn', 'NGN'), ('usd', 'USD')], max_length=5)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='commission',
            name='size',
            field=models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3')], max_length=5),
        ),
    ]
