# Generated by Django 6.0.7 on 2026-07-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_artwork_alter_commission_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'Currently Available'), ('sold', 'Sold Out'), ('NFS', 'Not For Sale'), ('notavail', 'Currently Not Available')], default='available', max_length=50),
        ),
    ]
