# Generated by Django 6.0.7 on 2026-07-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_artwork_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='price',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='studio.artwork')),
            ],
            options={
                'unique_together': {('artwork', 'currency')},
            },
        ),
    ]
